CREATE TABLE QuartelGrades
(
	ID SERIAL PRIMARY KEY,
	EmployeesId INTEGER REFERENCES employees (id),
	Q1 CHARACTER VARYING(2) NOT NULL,
	Q2 CHARACTER VARYING(2) NOT NULL,
	Q3 CHARACTER VARYING(2) NOT NULL,
	Q4 CHARACTER VARYING(2) NOT NULL
);