CREATE TABLE employees
(
	ID SERIAL PRIMARY KEY,
	LastName CHARACTER VARYING(30) NOT NULL,
	FirstName CHARACTER VARYING(30) NOT NULL,
	Patronymic CHARACTER VARYING(30) NOT NULL,
	BirthDate DATE NOT NULL,
	StartDate DATE NOT NULL,
	JobTitle CHARACTER VARYING(30) NOT NULL,
	ExperienceLevel CHARACTER VARYING(30) NOT NULL,
	Salary MONEY NOT NULL,
	DepartmentId INTEGER,
	Permentions BOOLEAN NOT NULL
);
