CREATE TABLE departments
(
	ID SERIAL PRIMARY KEY,
	DepartmentName CHARACTER VARYING(30),
	LastName CHARACTER VARYING(30) NOT NULL,
	FirstName CHARACTER VARYING(30) NOT NULL,
	Patronymic CHARACTER VARYING(30) NOT NULL,
	NumberEmployees INTEGER
);